REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
ALTER TABLE oidc_login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE oidc_login_attempts FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON oidc_login_attempts TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY identity_access ON oidc_login_attempts TO platform_auth USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE ON oidc_login_attempts TO platform_auth;
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizations FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON organizations TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON organizations TO platform_app USING (id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT ON organizations TO platform_app;
GRANT UPDATE (revision) ON organizations TO platform_app;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON users TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY identity_access ON users TO platform_auth USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE ON users TO platform_auth;
ALTER TABLE auth_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_events FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON auth_events TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY identity_access ON auth_events TO platform_auth USING (true) WITH CHECK (true);
GRANT SELECT, INSERT ON auth_events TO platform_auth;
ALTER TABLE cost_catalog_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cost_catalog_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON cost_catalog_versions TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON cost_catalog_versions TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT ON cost_catalog_versions TO platform_app;
ALTER TABLE organization_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON organization_memberships TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON organization_memberships TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT, UPDATE ON organization_memberships TO platform_app;
CREATE POLICY own_membership ON organization_memberships FOR SELECT TO platform_auth USING (user_id = NULLIF(current_setting('app.authenticated_user_id', true), '')::uuid);
GRANT SELECT ON organization_memberships TO platform_auth;
ALTER TABLE provider_budget_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_budget_days FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON provider_budget_days TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON provider_budget_days TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT, UPDATE ON provider_budget_days TO platform_app;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON audit_events TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON audit_events TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON audit_events TO platform_app;
ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_sessions FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON auth_sessions TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY identity_access ON auth_sessions TO platform_auth USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE ON auth_sessions TO platform_auth;
ALTER TABLE company_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_profiles FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON company_profiles TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON company_profiles TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT, UPDATE ON company_profiles TO platform_app;
ALTER TABLE membership_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership_roles FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON membership_roles TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON membership_roles TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON membership_roles TO platform_app;
CREATE POLICY own_membership ON membership_roles FOR SELECT TO platform_auth USING (user_id = NULLIF(current_setting('app.authenticated_user_id', true), '')::uuid);
GRANT SELECT ON membership_roles TO platform_auth;
ALTER TABLE company_profile_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_profile_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON company_profile_versions TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON company_profile_versions TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON company_profile_versions TO platform_app;
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessments FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON assessments TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON assessments TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON assessments TO platform_app;
ALTER TABLE infrastructure_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE infrastructure_assets FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON infrastructure_assets TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON infrastructure_assets TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON infrastructure_assets TO platform_app;
ALTER TABLE workloads ENABLE ROW LEVEL SECURITY;
ALTER TABLE workloads FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON workloads TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON workloads TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON workloads TO platform_app;
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON agent_runs TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON agent_runs TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON agent_runs TO platform_app;
ALTER TABLE architecture_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE architecture_candidates FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON architecture_candidates TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON architecture_candidates TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON architecture_candidates TO platform_app;
ALTER TABLE explanation_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE explanation_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON explanation_requests TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON explanation_requests TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT, UPDATE ON explanation_requests TO platform_app;
ALTER TABLE cost_estimate_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE cost_estimate_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_access ON cost_estimate_lines TO platform_migrator USING (true) WITH CHECK (true);
CREATE POLICY tenant_access ON cost_estimate_lines TO platform_app USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
GRANT SELECT, INSERT ON cost_estimate_lines TO platform_app;
CREATE POLICY own_organizations ON organizations FOR SELECT TO platform_auth USING (id IN (SELECT organization_id FROM organization_memberships WHERE status = 'ACTIVE'));
GRANT SELECT ON organizations TO platform_auth;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
